-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyzJzGAoq7PD9VWlX
FCTomBTRfhME9tNiUQJEhRwMBbugCgYIKoZIzj0DAQehRANCAAT5aTlegcehA7dT
r9RrhXwGmID6wwi8xoOnnQlXy9LUkwNDZbMsEerhSXdqgAccJUbsyYt/+j7xRHUQ
PLyoj6+h
-----END PRIVATE KEY-----